UsersAndRewards/UsersAndRewards.PL.Web/Models/RewardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using UsersAndRewards.Shared;

namespace UsersAndRewards.PL.Web.Models
{
    public class RewardViewModel
    {
        public int RewardId { get; set; }

        public string Title { get; set; }

        public bool IsChecked { get; set; }

        public static RewardViewModel ToModel(
            Reward reward,
            bool isChecked)
        {
            var model = new RewardViewModel();
            model.RewardId = reward.ID;
            model.Title = reward.Title;
            model.IsChecked = isChecked;

            return model;
        }
    }
}

UsersAndRewards/UsersAndRewards.PL.Web/Models/UsersAndRewardsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using UsersAndRewards.Shared;

namespace UsersAndRewards.PL.Web.Models
{
    public class UsersAndRewardsViewModel
    {
        public User User { get; set; }

        public List<RewardViewModel> AllRewards { get; set; }

        public static UsersAndRewardsViewModel CreateModel(User user, List<Reward> rewards)
        {
            var model = new UsersAndRewardsViewModel();
            model.User = user;
            model.AllRewards = new List<RewardViewModel>();
            foreach (Reward r in rewards)
            {
                var isChecked = user == null ? false : ContainsReward(r,user.Rewards);
                var rewardModel = RewardViewModel.ToModel(r, isChecked);
                model.AllRewards.Add(rewardModel);
            }

            return model;
        }
        private static bool ContainsReward(Reward reward, List<Reward> rewards)
        {
            foreach (var rewardTemp in rewards)
            {
                if (rewardTemp.ID == reward.ID)
                {
                    return true;
                }

            }
            return false;
        }
    }
}

UsersAndRewards/UsersAndRewards.PL.Web/Controllers/RewardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsersAndRewards.BL.Logic;
using UsersAndRewards.PL.Web.Models;
using UsersAndRewards.Shared;

namespace UsersAndRewards.PL.Web.Controllers
{
    public class RewardController : Controller
    {
        private ILogic logic;
        public RewardController()
        {
            logic = new Logic();
        }
        public ActionResult RewardTable()
        {
            var rewards = logic.GetRewards();
            return View("RewardPage",rewards);
        }
        public ActionResult Create()
        {
            return View("AddReward");
        }
        public ActionResult Update(int rewardID)
        {
            var model = logic.GetRewardById(rewardID);
            return View("AddReward", model);
        }
        public ActionResult Add(Reward reward)
        {
            if (reward.ID==0)
            {
                logic.AddReward(reward);
            }
            else
            {
                logic.UpdateReward(reward);
            }
            return RedirectToAction("RewardTable");
        }
        public ActionResult Delete(int rewardID)
        {
            logic.DeleteReward(rewardID);
            return RedirectToAction("RewardTable");
        }
    }
}

UsersAndRewards/UsersAndRewards.PL.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsersAndRewards.BL.Logic;
using UsersAndRewards.PL.Web.Models;
using UsersAndRewards.Shared;

namespace UsersAndRewards.PL.Web.Controllers
{
    public class UserController : Controller
    {
        private ILogic logic;
        public UserController()
        {
            logic = new Logic();
        }
        public ActionResult Index()
        {
            var users = logic.GetUsersViewModel();
            return View(users);
        }
        public ActionResult Create()
        {
            var model = UsersAndRewardsViewModel.CreateModel(null, logic.GetRewards());
            return View("UserPage", model);
        }
        public ActionResult Update(int userId)
        {
            var model = UsersAndRewardsViewModel.CreateModel(logic.GetUserById(userId), logic.GetRewards());
            return View("UserPage", model);
        }
        public ActionResult Add(UsersAndRewardsViewModel model)
        {
            var checkedRewards = model.AllRewards.Where(r => r.IsChecked).ToList();
            model.User.Rewards = checkedRewards.Select(m => new Reward { ID = m.RewardId }).ToList();
            if (model.User.ID==0)
            {
                logic.AddUser(model.User);
            }
            else
            {
                logic.UpdateUser(model.User);
            }
            return RedirectToAction("Index");
        }
        public ActionResult DeleteUser(int userId)
        {
            logic.DeleteUser(userId);
            return RedirectToAction("Index");
        }
    }
}

UsersAndRewards/UsersAndRewards.PL.Web/Views/Reward/AddReward.cshtml
@using UsersAndRewards.Shared;
@model Reward
@{
    ViewBag.Title = "AddReward";
}

<h2>AddReward</h2>

<form method="POST" action="Add">
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="control-label col-md-2">Title</label>
            <div class="col-md-10">
                <!--<input type="text" name="FirstName" class="form-control" value="model.FirstName"/>   -->
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @if (!(Model is null))
             {
                 @Html.HiddenFor(model => model.ID)
             }
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Description</label>.
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "RewardTable")
</div>

UsersAndRewards/UsersAndRewards.PL.Web/Views/Reward/RewardPage.cshtml
@using UsersAndRewards.Shared;
@{
    ViewBag.Title = "RewardPage";
}

@model List<Reward>
<h2>Rewards</h2>

<p>
    @Html.ActionLink("Create New Reward", "Create")
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reward in Model)
        {
            <tr>
                <td>@reward.Title</td>
                <td>@reward.Description</td>
                <td>
                    @Html.ActionLink("Edit", "Update", new { RewardId = reward.ID })
                    @Html.ActionLink("Delete", "Delete", new { RewardId = reward.ID })
                </td>
            </tr>
        }
    </tbody>
</table>

UsersAndRewards/UsersAndRewards.PL.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <table>
                    <tr>
                        <td>@Html.ActionLink("Users", "Index", "User",new { area = "" }, new { @class = "navbar-brand" })</td>
                        <td>@Html.ActionLink("Rewards", "RewardTable","Reward",new { area = "" }, new { @class = "navbar-brand" })</td>
                    </tr>
                </table>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

UsersAndRewards/UsersAndRewards.PL.Web/Views/User/Index.cshtml
@using UsersAndRewards.Shared;
@model List<UserViewModel>


@{
    ViewBag.Title = "Index";
}

<h2>Users</h2>

<p>
    @Html.ActionLink("Create New User", "Create")
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>DateOfBirth</th>
            <th>Age</th>
            <th>Rewards</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.FirstName</td>
                <td>@user.LastName</td>
                <td>@user.DateOfBirth.ToShortDateString()</td>
                <td>@user.Age</td>
                <td>@user.Rewards</td>
                <td>
                    @Html.ActionLink("Edit", "Update", new { UserId = user.ID })
                    @Html.ActionLink("Delete", "DeleteUser", new { UserId = user.ID })
                </td>
            </tr>
        }
    </tbody>

</table>

UsersAndRewards/UsersAndRewards.PL.Web/Views/User/UserPage.cshtml
@model UsersAndRewards.PL.Web.Models.UsersAndRewardsViewModel

@{
    ViewBag.Title = "User";
}

<h2>Add User</h2>

<form method="POST" action="Add">
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="control-label col-md-2">First Name</label>
            <div class="col-md-10">
                <!--<input type="text" name="FirstName" class="form-control" value="model.FirstName"/>   -->
                @if (!(Model.User is null))
                 {
                    @Html.HiddenFor(model => model.User.ID)
                 }
                @Html.EditorFor(model => model.User.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Last Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Birthdate</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Rewards</label>
            <div class="col-md-10">
                @for (var i = 0; i < Model.AllRewards.Count; i++)
                {
                    @Html.EditorFor(model => model.AllRewards[i].IsChecked)
                    <span>@Model.AllRewards[i].Title</span>
                    @Html.HiddenFor(model => model.AllRewards[i].RewardId)
                    <br />
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>